/**
 * Cross-validation test: compares values from our JS API extraction
 * against fixtures generated by policyengine-us Python package.
 *
 * Fixtures are generated by: python3 scripts/generate-fixtures.py
 * This ensures our JS code extracts the same values the Python engine computes.
 */

import { describe, it, expect, beforeAll } from "vitest";
import { getPrograms } from "../src/api.js";
import fixtures from "./fixtures.json";

const TOLERANCE = 2; // $2 tolerance for floating-point differences

const SCENARIOS = [
  { label: "Married CA $45k/$45k no kids", args: ["us", "CA", 45000, { head: false, spouse: false }, 45000, [], "2026"] },
  { label: "Single CA $20k 1 child(5)", args: ["us", "CA", 20000, { head: false }, null, [{ age: 5 }], "2026"] },
  { label: "Low-income CA $10k 1 child(3)", args: ["us", "CA", 10000, { head: false }, null, [{ age: 3 }], "2026"] },
  { label: "Married NY $80k/$40k 2 kids", args: ["us", "NY", 80000, { head: false, spouse: false }, 40000, [{ age: 8 }, { age: 12 }], "2026"] },
  { label: "Single TX $0 no kids (zero income)", args: ["us", "TX", 0, { head: false }, null, [], "2026"] },
];

for (const scenario of SCENARIOS) {
  describe(`Audit: ${scenario.label}`, () => {
    let r;
    const expected = fixtures[scenario.label];

    beforeAll(async () => {
      r = await getPrograms(...scenario.args);
    }, 60000);

    it("aggregates match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.aggregates)) {
        const actual = r.aggregates[key];
        console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        expect(
          Math.abs((actual || 0) - expectedVal),
          `aggregate ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("benefits match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.benefits)) {
        const actual = r.benefits[key];
        if (expectedVal !== 0 || (actual && actual !== 0)) {
          console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        }
        expect(
          Math.abs((actual || 0) - expectedVal),
          `benefit ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("credits match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.credits)) {
        const actual = r.credits[key];
        if (expectedVal !== 0 || (actual && actual !== 0)) {
          console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        }
        expect(
          Math.abs((actual || 0) - expectedVal),
          `credit ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("taxes match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.taxes)) {
        const actual = r.taxes[key];
        if (expectedVal !== 0 || (actual && actual !== 0)) {
          console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        }
        expect(
          Math.abs((actual || 0) - expectedVal),
          `tax ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("healthcare match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.health)) {
        const actual = r.health[key];
        if (expectedVal !== 0 || (actual && actual !== 0)) {
          console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        }
        expect(
          Math.abs((actual || 0) - expectedVal),
          `health ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("state credits match Python fixtures", () => {
      for (const [key, expectedVal] of Object.entries(expected.stateCredits)) {
        const actual = r.stateCredits[key];
        if (expectedVal !== 0 || (actual && actual !== 0)) {
          console.log(`    ${key}: API=$${actual?.toFixed(2)} Python=$${expectedVal}`);
        }
        expect(
          Math.abs((actual || 0) - expectedVal),
          `stateCredit ${key}: got ${actual}, expected ${expectedVal}`,
        ).toBeLessThan(TOLERANCE);
      }
    });

    it("net income identity holds", () => {
      const { householdNetIncome, householdBenefits, householdRefundableCredits, householdTaxBeforeCredits } = r.aggregates;
      const income = scenario.args[2] + (scenario.args[4] || 0);
      const computed = income + householdBenefits + householdRefundableCredits - householdTaxBeforeCredits;
      const diff = computed - householdNetIncome;

      console.log(`    income=$${income} + benefits=$${householdBenefits.toFixed(2)} + credits=$${householdRefundableCredits.toFixed(2)} - taxes=$${householdTaxBeforeCredits.toFixed(2)} = $${computed.toFixed(2)} vs net=$${householdNetIncome.toFixed(2)} (diff=$${diff.toFixed(2)})`);

      expect(Math.abs(diff)).toBeLessThan(Math.max(10, Math.abs(householdNetIncome) * 0.01));
    });
  });
}
